version: "3.3"

services:
  api_dev:
    container_name: api_dev
    image: ductin_api_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - ductin
networks:
  ductin:
    external: true
